### ISSUE TITLE
About inferencing or training lerobot's Diffusion Policy 

### ISSUE THREAD

**Issue by zimka** [kywch/mg2hfbot#1]
Hi, thank you for publishing your project and providing it with clear docs!
Do you have plans (or have you already tried) to train diffusion policy on any of these converted MimicGen datasets?
As far as I see there are ACT and BCRNN checkpoints available at your HuggingFace space, but no DP.  Is there any particular reason?
Thanks!

**Comment by kywch** [comment]
Hello, thank you for the kind message!

I tried diffusion policies, but the results weren't good, so I didn't upload them.

The LeRobot Discord community mentioned that the hyperparam for the diffusion policy were optimized for the push-t task, and suggested experimenting with different hyperparams. This could be a great project for someone with computing resources.
