### ISSUE TITLE
Error in train script

### ISSUE THREAD

**Issue by MarijaGolubovic** [kywch/mg2hfbot#2]
Hi,
First of all, thank you for your project. I tried to reproduce your results and found a few errors.

  1. I found a spelling error in the `train.py` script. On line 212, the function `save_checkpont` is missing the letter i in the word "checkpoint."

   2. When I run the training script, I need to remove all arguments from the command provided in the README file. Otherwise, I get an error related to non-existing arguments.

   3. Inside the YAML files in the `config/env` directory, the parameter `use_delta_action` is set to `True`, but there is no support implemented for delta actions. Because of this, I get a warning at the beginning.

Thanks!

**Comment by kywch** [comment]
Hello, thank you for the feedback!

1. I fixed the function name to `checkpoint`. 

2. The previous training command was wrong, and I fixed the README file. `train.py` is based on hydra, and `eval.py`/`convert_to_lerobot.py` are based on argparse, so passing args is different between these.

3. Can you please let me know the command and warning, so that I can look into it?

Thank you so much!

**Comment by MarijaGolubovic** [comment]
Hi, thank you for response.  

Inside the previously mentioned YAML files, the parameter `use_delta_action` is set to `True`. This parameter activates the following case inside training script:

```sh
 elif cfg.policy.name == "diffusion":
        if cfg.env.use_delta_action:
            logging.warning(
                "Diffusion should NOT use delta actions. Setting cfg.env.use_delta_action to False."
            )
            cfg.env.use_delta_action = False
        assert (
            image_obs_shape[1] == IMAGE_OBS_SIZE[0] and image_obs_shape[2] == IMAGE_OBS_SIZE[1]
        ), "Image obs shape does not match image obs size"
```

Thanks!

**Comment by MarijaGolubovic** [comment]
Also, I have another suggestion for the README file. You included a `$` prefix at the beginning of each command. Because of this, I need to copy each command one by one, and I can't simply click the copy button and paste everything into the terminal.

Thank you!

**Comment by kywch** [comment]
Thank you for the additional information and suggestions.

The `use_delta_action` flag pertains to the different action spaces used by BC-RNN and ACT/diffusion. The training script automatically sets this flag and displays a warning. I've added a note about this in the README.

As you suggested, I've removed the shell prefixes from the README commands to facilitate copy-and-paste into the CLI.

Please let me know if you have any questions or suggestions. Thank you!

**Comment by MarijaGolubovic** [comment]
Thank you for applying my suggestion. I'm glad I could help improve your repository. That's all for now. Good luck with your project!

**Comment by kywch** [comment]
Thank you for your kind words, and good luck with your projects too!
